cloud:
    aws:
        credentials:
            access-key:
            secret-key:
        region:
            static: eu-west-1
        stack:
            auto: false

application:
    bucket:
        name: autopartsmanager-file

jwt:
    auth:
        converter:
            resource-id: autopartsmanager-service-client
            principle-attribute: preferred_username


spring:
    security:
        oauth2:
            resourceserver:
                jwt:
                  issuer-uri: http://localhost:8520/realms/autopartsmanager
                  jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs


    servlet:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB
    datasource:
        url: jdbc:mysql://localhost/autopartsmanager?createDatabaseIfNotExist=true
        username: root
        password:
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
server:
    servlet:
        context-path: /api
    port: 9090

myKeycloak:
  http:
    users-endpoint: http://localhost:8520/admin/realms/autopartsmanager/users
    token-endpoint: http://localhost:8520/realms/autopartsmanager/protocol/openid-connect/token
    logout-endpoint: http://localhost:8520/realms/autopartsmanager/protocol/openid-connect/logout
    roles-endpoint: http://localhost:8520/admin/realms/autopartsmanager/roles

  client:
    default-role-id: 1bef3c1f-dbf3-4823-8e9e-721810ed09db
    default-role-name: client

